### PR TITLE
CI

### PR DESCRIPTION
**Pull request by htalat**
#18 
runs CI whenever there's a push to the main branch i.e. master or can be triggered manually from the actions tab.

Right now it just runs the preProcessor.

### CODE REVIEW

**Comment by htalat** [comment]
a couple of [bad xmls](https://github.com/htalat/makhzan/runs/1218455586?check_suite_focus=true) found lol

**Comment by zeerakahmed** [comment]
What changes did we make to 0001.xml and 0002.xml? Do you remember?
Other stuff looks good.

**Comment by htalat** [comment]
oh. good catch. i copied those two files over to a separate directory `tex`  to test. I'll remove them.

**Comment by htalat** [comment]
Should be good now.

**Comment by zeerakahmed** [comment]
Thanks!

**Pull request merged**
